// components/SearchBar/SearchBarDropdownItem.tsx
import type { ReactNode } from "react";

interface SearchBarDropdownItemProps {
  isSelected?: boolean;
  onHover?: () => void;
  children: ReactNode;
}

export function SearchBarDropdownItem({ isSelected, onHover, children }: SearchBarDropdownItemProps) {
  return (
    <div className={`p-2 ${isSelected ? "bg-focused-primary" : ""}`} onMouseEnter={onHover}>
      {children}
    </div>
  );
}

// src/lib/components/SearchBar/SearchBarDropdownItem.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		isSelected?: boolean;
		onHover?: () => void;
		children: Snippet;
	}

	let { isSelected = false, onHover, children }: Props = $props();
</script>

<div
	class="p-2 {isSelected ? 'bg-focused-primary' : ''}"
	onmouseenter={onHover}
	role="option"
	aria-selected={isSelected}
	tabindex="-1"
>
	{@render children()}
</div>
