// components/SearchBar/SearchBarDropdownMenu.tsx
import type { SearchEntity } from "@/types/search";
import { SearchBarDropdownItem } from "./SearchBarDropdownItem";
import { SearchBookItem } from "./SearchBookItem";

interface SearchBarDropdownMenuProps {
  books: SearchEntity[];
  isLoading: boolean;
  error: string | null;
  selectedIndex: number;
  query: string;
  onItemHover: (index: number) => void;
  onItemSelect: () => void;
}

export function SearchBarDropdownMenu({
  books,
  isLoading,
  error,
  selectedIndex,
  query,
  onItemHover,
  onItemSelect,
}: SearchBarDropdownMenuProps) {
  return (
    <div className="absolute top-full left-0 right-0 bg-bgd-secondary border border-t-0 border-border-primary z-10">
      {error && <div className="p-4">Error: {error}</div>}

      {!error && books.length === 0 && !isLoading && <div className="p-4">No books found</div>}

      {!error && books.length > 0 && (
        <div className="vstack">
          {books.map((result, index) => (
            <SearchBarDropdownItem
              key={result.uri}
              isSelected={index === selectedIndex}
              onHover={() => onItemHover(index)}
            >
              <SearchBookItem result={result} onSelect={onItemSelect} />
            </SearchBarDropdownItem>
          ))}
          <div className="pt-2">
            <a href={`/search?q=${encodeURIComponent(query)}`}>View more results</a>
          </div>
        </div>
      )}

      {isLoading && books.length === 0 && <div className="p-4">Searching...</div>}
    </div>
  );
}

// src/lib/components/SearchBar/SearchBarDropdownMenu.svelte
<script lang="ts">
	import type { SearchEntity } from '$lib/inventaire/requests/search/types/search';
	import SearchBarDropdownItem from './SearchBarDropdownItem.svelte';
	import SearchEntityItem from './SearchEntityItem.svelte';

	interface Props {
		results: SearchEntity[];
		isLoading: boolean;
		error: string | null;
		selectedIndex: number;
		query: string;
		onItemHover: (index: number) => void;
		onItemSelect: () => void;
	}

	let { results, isLoading, error, selectedIndex, query, onItemHover, onItemSelect }: Props =
		$props();
</script>

<div
	class="absolute top-full right-0 left-0 z-10 border border-t-0 border-border-primary bg-bgd-secondary"
>
	{#if error}
		<div class="p-4">Error: {error}</div>
	{/if}

	{#if !error && results.length === 0 && !isLoading}
		<div class="p-4">No books found</div>
	{/if}

	{#if !error && results.length > 0}
		<div class="vstack">
			{#each results as result, index}
				<SearchBarDropdownItem
					isSelected={index === selectedIndex}
					onHover={() => onItemHover(index)}
				>
					<SearchEntityItem {result} onSelect={onItemSelect} />
				</SearchBarDropdownItem>
			{/each}
			<div class="pt-2">
				<a href="/search?q={encodeURIComponent(query)}">View more results</a>
			</div>
		</div>
	{/if}

	{#if isLoading && results.length === 0}
		<div class="p-4">Searching...</div>
	{/if}
</div>
